# Generated by Django 5.0.7 on 2024-07-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=100, unique=True)),
                ('loading_port', models.CharField(max_length=100)),
                ('discharge_port', models.CharField(max_length=100)),
                ('ship_arrival_date', models.DateField()),
                ('ship_departure_date', models.DateField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date Create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date Create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bookings.booking')),
            ],
        ),
    ]
