# Generated by Django 5.0.7 on 2024-07-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discharge_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_bookings', to='bookings.port'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='loading_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_bookings', to='bookings.port'),
        ),
    ]
